name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create .env file
      run: cp .env.example .env

    - name: Build the Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag tritonfit-backend:$(date +%s)

    - name: Run Tests with Coverage
      working-directory: ./backend
      env:
        MONGODB_URL: mongodb://mongodb:27017
        DATABASE_NAME: tritonfit_test
        SECRET_KEY: test_secret_key
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
      run: |
        docker compose build
        docker compose run --rm test pytest tests/ -v --cov=app --cov-report=term-missing 